"""Add Cloudflare and Smartlead API fields

Revision ID: 104983f120a9
Revises: d3dca68d6f6d
Create Date: 2024-09-07 21:09:33.042648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104983f120a9'
down_revision = 'd3dca68d6f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudflare_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cloudflare_api_key', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('smartlead_api_key', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('smartlead_api_key')
        batch_op.drop_column('cloudflare_api_key')
        batch_op.drop_column('cloudflare_email')

    # ### end Alembic commands ###
