"""empty message

Revision ID: 320d7552ca72
Revises: 643e40d18f0c
Create Date: 2024-09-08 15:37:48.811666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320d7552ca72'
down_revision = '643e40d18f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_to_server', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('added_to_server')

    # ### end Alembic commands ###
