"""Remove mailbox_type from Mailbox model

Revision ID: 643e40d18f0c
Revises: 866cc499686c
Create Date: 2024-09-08 09:55:30.266508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643e40d18f0c'
down_revision = '866cc499686c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailbox', schema=None) as batch_op:
        batch_op.drop_column('mailbox_type')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('mailbox_type', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
