"""Update Mailbox model with user_id and other fields

Revision ID: 866cc499686c
Revises: 5e1b6368ee88
Create Date: 2024-09-08 09:14:59.068791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866cc499686c'
down_revision = '5e1b6368ee88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('email_signature', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('message_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minimum_time_gap', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_warmup_per_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_rampup', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reply_rate_percentage', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mailbox_user_id', 'user', ['user_id'], ['id'])  # Named foreign key constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mailbox', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mailbox_user_id', type_='foreignkey')  # Use the constraint name
        batch_op.drop_column('reply_rate_percentage')
        batch_op.drop_column('daily_rampup')
        batch_op.drop_column('total_warmup_per_day')
        batch_op.drop_column('minimum_time_gap')
        batch_op.drop_column('message_per_day')
        batch_op.drop_column('email_signature')
        batch_op.drop_column('company_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###