"""Initial migration with Stripe fields

Revision ID: d3dca68d6f6d
Revises: c2245d5c18ae
Create Date: 2024-09-07 20:00:58.576870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3dca68d6f6d'
down_revision = 'c2245d5c18ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_plan_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_plan_id')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
